<a href="https://colab.research.google.com/github/GuiOSousa/HouseValueRegression/blob/RandomForestRegressor/HouseValue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preparando o Ambiente

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Tratando os Dados

##Acessando a base de dados

In [ ]:
import pandas as pd

dataset = pd.read_csv('/content/drive/MyDrive/Datasets/HouseRentData/house_prices.csv')

dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY,342200
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,INLAND,78100
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,INLAND,77100
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND,92300
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND,84700
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND,89400

##Tratando valores NaN e nulos

In [ ]:
print(dataset.isna().sum())
print(dataset.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

Como nossos valores NaN/nulos representam uma parcela mínima da nossa base de dados, podemos optar por simplesmente excuí-los, sem que haja impactos significantes no treinamento do modelo

In [ ]:
dataset = dataset.dropna()
dataset = dataset.reset_index(drop=True)

##Decodificando valores de texto em valores numéricos

Modelos de linguagem geralmente requerem uma decodificação quando trabalhamos com Strings.


No bloco abaixo, substituimos a "distância do mar", atributo descrito em texto, por valores inteiros.

In [ ]:
datasetEncoded = dataset[:]

datasetEncoded = datasetEncoded.replace("ISLAND", 0)
datasetEncoded = datasetEncoded.replace("NEAR BAY", 1)
datasetEncoded = datasetEncoded.replace("NEAR OCEAN", 2)
datasetEncoded = datasetEncoded.replace("<1H OCEAN", 3)
datasetEncoded = datasetEncoded.replace("INLAND", 4)

datasetEncoded

<ipython-input-16-edbe6781ec6d>:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datasetEncoded = datasetEncoded.replace("INLAND", 4)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,1,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,1,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,1,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,1,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,1,342200
...,...,...,...,...,...,...,...,...,...,...
20428,-121.09,39.48,25,1665,374.0,845,330,1.5603,4,78100
20429,-121.21,39.49,18,697,150.0,356,114,2.5568,4,77100
20430,-121.22,39.43,17,2254,485.0,1007,433,1.7000,4,92300
20431,-121.32,39.43,18,1860,409.0,741,349,1.8672,4,84700
20432,-121.24,39.37,16,2785,616.0,1387,530,2.3886,4,89400

##Atributos de posição

Embora Latitude e Longitude não sejam os melhores atributos para se analisar quando fatores socioeconômicos são mais importantes que a posição física do objeto em questão, materemos ambas pois não possuímos, na base de dados, outros dados referentes a localização.

No contexto dado, informações como estado, cidade/distrito, bairros, etc. trariam análises mais relevantes, portanto seria mais prudente remover as colunas de Latitude e Longitude.*texto em itálico*

#Separando Teste e Treinamento

In [ ]:
trainingDataset = datasetEncoded.sample(frac=0.9)

trainingDataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
11479,-118.07,33.80,34,3486,507.0,1311,503,7.1221,3,384500
10555,-117.81,33.66,20,2851,490.0,1192,463,5.8752,3,274200
20326,-121.67,38.54,13,6141,1019.0,2553,967,4.2432,4,326500
5510,-118.28,33.88,19,2758,675.0,2047,591,2.6618,3,179700
9636,-121.72,36.81,18,1984,379.0,1078,359,3.2969,3,229900
...,...,...,...,...,...,...,...,...,...,...
5708,-118.27,34.16,47,1453,356.0,787,345,3.0114,3,255500
17012,-122.47,37.50,25,950,259.0,404,195,3.1937,2,319200
10286,-117.65,33.58,2,2411,354.0,703,217,7.8061,3,331400
10471,-117.69,33.64,18,3783,654.0,1843,623,5.7559,3,215800
16999,-122.21,37.37,34,1476,217.0,613,223,8.2883,2,500001

In [ ]:
X_trainingDataset = trainingDataset.drop("median_house_value", axis=1)
Y_trainingDataset = trainingDataset.drop(X_trainingDataset, axis=1)

In [ ]:
testDataset = datasetEncoded.drop(trainingDataset.index)

testDataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
6,-122.25,37.84,52,2535,489.0,1094,514,3.6591,1,299200
14,-122.26,37.85,52,2643,626.0,1212,620,1.9167,1,159200
20,-122.27,37.85,40,751,184.0,409,166,1.3578,1,147500
24,-122.27,37.84,52,2224,437.0,1006,422,2.6000,1,132600
51,-122.27,37.82,43,1868,456.0,1061,407,1.5045,1,93800
...,...,...,...,...,...,...,...,...,...,...
20362,-121.76,38.66,17,5320,984.0,2866,928,4.1997,4,133400
20378,-122.04,38.68,26,1113,222.0,689,234,3.0486,4,83600
20407,-121.54,39.08,26,2276,460.0,1455,474,2.4695,4,58000
20416,-121.37,39.03,32,1158,244.0,598,227,2.8235,4,65500
20432,-121.24,39.37,16,2785,616.0,1387,530,2.3886,4,89400

In [ ]:
X_testDataset = testDataset.drop("median_house_value", axis=1)
Y_testDataset = testDataset.drop(X_testDataset, axis=1)

#Gradient Boosting Regressor
Utilizamos um Gradient Boosting Regressor genérico (sem alteração nos hiperparâmetros) para a tarefa de regressão.

O Gradient Boosting Regressor é um modelo de ensemble (combina modelos mais fracos em modelos mais fortes durante o treinamento) de Árvores de Decisão de forma sequencial.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

model = GradientBoostingRegressor()

model.fit(X_trainingDataset, Y_trainingDataset)

prediction = model.predict(X_testDataset)

/usr/local/lib/python3.11/dist-packages/sklearn/ensemble/_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

In [ ]:
predictionDataFrame = pd.DataFrame(prediction)

predictionDataFrame

                  0
0     249111.475983
1     170946.589862
2     146673.029602
3     195755.873409
4     154637.756625
...             ...
2038  153596.898285
2039  103539.901569
2040   86451.115116
2041  101851.737801
2042   89120.580787

[2043 rows x 1 columns]

##Avaliando as predições

Métricas comuns como MAE e MSE são difíceis de interpretar pois nossos valores não estão normalizados, então MAPE, RSMLE e R² foram escolhidas.

Como nossos resultados são predições de preços de propriedades, que apresentam valores na casa das centenas de milhar, MAE e MSE apresentariam valores extremamente altos independente da qualidade do modelo, portanto, pouco confiáveis para dizer a qualidade das previsões.

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_log_error, r2_score
import numpy as np


mape = mean_absolute_percentage_error(Y_testDataset, predictionDataFrame)
msle = mean_squared_log_error(Y_testDataset, predictionDataFrame)
r2 = r2_score(Y_testDataset, predictionDataFrame)
rmsle = np.sqrt(msle)

print(f"MAPE: {mape:.2f}")
print(f"RMSLE: {rmsle:.2f}")
print(f"R2: {r2:.2f}")

MAPE: 0.21
RMSLE: 0.27
R2: 0.77

Analisando os valores de MAPE, RSMLE e R², podemos concluir que os resultados foram aceitáveis para um modelo genérico, considerando também que váriaveis de localização melhores levariam a predições mais precisas.

A pouca diferença entre MAPE (Mean Absolute Percentage Error) e RMSLE (Root Mean Squared Logarithmic Error) indica que não houve uma grande quantidade de erros críticos, em que os valores da predição e da verdade são completamente destoantes.

##Plotagem do Mapa

In [ ]:
import folium
from folium.plugins import *
from google.colab import output

map = folium.Map(tiles='openstreetmap',location=[36.69245689448622, -119.7175285756223],zoom_start=7,zoom_control=True)

In [ ]:
import math

housesLayer = folium.FeatureGroup(name="Houses", show=True)

for i in range(len(testDataset)-1):
  house = testDataset.iloc[i]
  coordinates = [house['latitude'], house['longitude']]
  truePrice = Y_testDataset.iloc[i, 0]
  predictedPrice = int(predictionDataFrame.iloc[i,0])

  error = math.fabs((predictedPrice - truePrice)/truePrice)
  if error <= 0.05:
    color = 'blue'
  elif error <= 0.1:
    color = 'green'
  elif error <= 0.2:
    color = 'yellow'
  elif error <= 0.5:
    color = 'orange'
  else:
     color = 'red'



  housePopup = folium.Popup(f"Predicted Price: {predictedPrice}<br>Real Price: {int(truePrice)}", max_width=500)
  houseMarker = folium.CircleMarker(location=coordinates,
                                    popup= housePopup,
                                    fill_color = color,
                                    fill_opacity = 0.6,
                                    stroke = False,
                                     ).add_to(map)

housesLayer.add_to(map)

In [ ]:
map.save('map.html')
map

#Random Forest Regressor

O Random Forest Regressor é um modelo de ensemble que combina os resultados de Decision Trees. Diferente do GBR, este modelo cria as DTs de forma paralela, combinando apenas os resultados.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_trainingDataset, Y_trainingDataset)


y_pred = model.predict(X_testDataset)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

##Avaliando as Predições

Foram usadas as mesmas métricas do modelo anterior

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_log_error, r2_score
import numpy as np


mape = mean_absolute_percentage_error(Y_testDataset, y_pred)
msle = mean_squared_log_error(Y_testDataset, y_pred)
r2 = r2_score(Y_testDataset, y_pred)
rmsle = np.sqrt(msle)

print(f"MAPE: {mape:.2f}")
print(f"RMSLE: {rmsle:.2f}")
print(f"R2: {r2:.2f}")

MAPE: 0.17
RMSLE: 0.23
R2: 0.82

O RFR, quando comparado com o modelo GBR testado anteriormente, apresentou mlehora em todas as métricas comparadas.
Valores menores no MAPE indicam menores erros percentuais, no RSLE indicam erros menores na média e valores maiores no R2 indicam que o modelo explica melhor a variabilidade dos preços.

In [ ]:
predictionRandomForestRegressor = pd.DataFrame(y_pred)

predictionRandomForestRegressor

              0
0     255565.00
1     186952.00
2     140599.01
3     164266.00
4     125012.00
...         ...
2038  159242.00
2039  112207.00
2040   91685.00
2041  107988.00
2042   86787.00

[2043 rows x 1 columns]

##Plotagem do Mapa

In [ ]:
import folium
from folium.plugins import *
from google.colab import output

map = folium.Map(tiles='openstreetmap',location=[36.69245689448622, -119.7175285756223],zoom_start=7,zoom_control=True)

In [ ]:
import math

housesLayer = folium.FeatureGroup(name="Houses", show=True)

for i in range(len(testDataset)-1):
  house = testDataset.iloc[i]
  coordinates = [house['latitude'], house['longitude']]
  truePrice = Y_testDataset.iloc[i, 0]
  predictedPrice = int(predictionRandomForestRegressor.iloc[i,0])

  error = math.fabs((predictedPrice - truePrice)/truePrice)
  if error <= 0.05:
    color = 'blue'
  elif error <= 0.1:
    color = 'green'
  elif error <= 0.2:
    color = 'yellow'
  elif error <= 0.5:
    color = 'orange'
  else:
     color = 'red'



  housePopup = folium.Popup(f"Predicted Price: {predictedPrice}<br>Real Price: {int(truePrice)}", max_width=500)
  houseMarker = folium.CircleMarker(location=coordinates,
                                    popup= housePopup,
                                    fill_color = color,
                                    fill_opacity = 0.6,
                                    stroke = False,
                                     ).add_to(map)

housesLayer.add_to(map)

In [ ]:
map